version: '3.9'

networks:
    backend:
        driver: bridge

services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx.${SERVICE_NAME}
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - .:/var/www
            - ./sandbox/nginx/conf.d:/etc/nginx/conf.d
            - ./sandbox/nginx/logs:/var/log/nginx/
            - ./sandbox/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - backend
        depends_on:
            - php-8.2

    db:
        image: mysql:8.0
        container_name: mysql_db
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./sandbox/db/data:/var/lib/mysql
            - ./sandbox/db/conf.d:/etc/mysql/conf.d
            - ./sandbox/db/logs:/var/log/mysql/
            - ./sandbox/db/dump:/dump
        ports:
            - "3306:3306"
        networks:
            - backend
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

    php-8.2:
        build:
            context: sandbox/php/8.2
            dockerfile: Dockerfile
            args:
                DOCKER_PHP_VERSION: '8.2'
        working_dir: /var/www
        container_name: php-8.2.${SERVICE_NAME}
        volumes:
            - ./.ssh:/home/www-data/.ssh
            - .:/var/www
            - ./sandbox/php/8.2/php.ini:/usr/local/etc/php/php.ini
            - ./sandbox/php-workers/8.2/supervisor.d:/etc/supervisor.d
            - /home:/home
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - /etc/shadow:/etc/shadow:ro
        ports:
            - "9007:9000"
        networks:
            - backend
        extra_hosts:
            - "${SERVICE_HOST}:host-gateway"
        user: root
        depends_on:
            db:
                condition: service_healthy
        command: >
            sh -c "php artisan passport:keys --force && chmod -R 775 /var/www/storage && chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && php artisan migrate --force && php-fpm"

volumes:
    db_data:
